### ISSUE TITLE
Qv2ray 在弹出无法加载插件窗口时再启动新的 Qv2ray 导致的异常

### ISSUE THREAD

**Issue by unknowndev233** [Qv2ray/Qv2ray#1025]
- [x] **我确定我已经尝试多次触发此次问题，并且将会提供涉及此问题的系统环境，每个软件及其版本。**

## 简单描述这个 Bug:
就像标题那样

## 如何触发这个 Bug：

1. 保证主程序与插件版本不匹配
2. 启动 Qv2ray，这时候应该提示插件加载失败
3. 不要确定，再启动新的 Qv2ray
4. 收获异常

### 相关截图或日志

![image](https://user-images.githubusercontent.com/52807407/95862742-ea78b700-0d95-11eb-9860-cc30a9a7250e.png)

<details>

```
请从此行下面的行开始粘贴 Qv2ray 日志：

很遗憾，Qv2ray 日志和 stacktrace 在寻找这个问题的原因中没有起到一星半点的帮助  
<del>万般无奈之下只好自己冒着自己的 Arch 随时 kernel panic 的风险编译了带有 debug 符号的 Qv2ray</del>



gdb backtrace:
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f8ac990e46f in poll () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007f8ac990e46f in poll () from /usr/lib/libc.so.6
#1  0x00007f8ac88275af in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007f8ac87d2131 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007f8aca02b941 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007f8ac9fd165c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007f8acac9df6a in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#6  0x00007f8acacd36d6 in QMessageBox::warning(QWidget*, QString const&, QString const&, int, int, int) () from /usr/lib/libQt5Widgets.so.5
#7  0x000055f5d30f1202 in Qv2ray::common::QvMessageBoxWarn (parent=<optimized out>, title=..., text=...) at ../src/common/QvHelpers.cpp:219
#8  0x000055f5d2ff979a in signalHandler (signum=<optimized out>) at /usr/include/qt/QtCore/qstring.h:830
#9  <signal handler called>
#10 0x00007f8acaad8042 in QWidget::show() () from /usr/lib/libQt5Widgets.so.5
#11 0x000055f5d3008753 in Qv2ray::Qv2rayApplication::onMessageReceived (this=0x7ffe6afe0120, clientId=<optimized out>, _msg=...)
    at ../src/Qv2rayApplication.cpp:155
#12 0x000055f5d300a9e6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<unsigned int, QByteArray>, void, void (Qv2ray::Qv2rayApplication::*)(unsigned int, QByteArray)>::call (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt/QtCore/qrefcount.h:60
#13 QtPrivate::FunctionPointer<void (Qv2ray::Qv2rayApplication::*)(unsigned int, QByteArray)>::call<QtPrivate::List<unsigned int, QByteArray>, void> (
    arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#14 QtPrivate::QSlotObject<void (Qv2ray::Qv2rayApplication::*)(unsigned int, QByteArray), QtPrivate::List<unsigned int, QByteArray>, void>::impl (
    which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418
#15 0x00007f8ac9fff7e2 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007f8acaa9a752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007f8ac9fd2cda in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007f8ac9fd57d3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#19 0x00007f8aca02c304 in ?? () from /usr/lib/libQt5Core.so.5
#20 0x00007f8ac87d3924 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#21 0x00007f8ac8827621 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007f8ac87d2131 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007f8aca02b941 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#24 0x00007f8ac9fd165c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007f8acac9df6a in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#26 0x00007f8acacd36d6 in QMessageBox::warning(QWidget*, QString const&, QString const&, int, int, int) () from /usr/lib/libQt5Widgets.so.5
#27 0x000055f5d30f1202 in Qv2ray::common::QvMessageBoxWarn (parent=parent@entry=0x0, title=..., text=...) at ../src/common/QvHelpers.cpp:219
#28 0x000055f5d31106d7 in Qv2ray::components::plugins::QvPluginHost::RefreshPluginList (this=this@entry=0x55f5d393a500)
    at ../src/components/plugins/QvPluginHost.hpp:24
#29 0x000055f5d31134bd in Qv2ray::components::plugins::QvPluginHost::InitializePluginHost (this=this@entry=0x55f5d393a500)
    at ../src/components/plugins/QvPluginHost.cpp:130
#30 0x000055f5d31137e0 in Qv2ray::components::plugins::QvPluginHost::QvPluginHost (this=0x55f5d393a500, parent=<optimized out>)
    at ../src/components/plugins/QvPluginHost.cpp:20
#31 0x000055f5d3003d28 in Qv2ray::Qv2rayApplication::InitializeGlobalVariables (this=<optimized out>) at ../src/Qv2rayApplication.cpp:446
#32 0x000055f5d2ff7826 in RunQv2rayApplicationScoped (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:184
#33 0x000055f5d2ffa127 in main (argc=<optimized out>, argv=0x7ffe6afe0348) at ../src/main.cpp:229
```

</details>

### 打开首选项 -> 关于，填写以下信息

```
版本: 2.6.3:5841
```

### 操作系统

- Linux

### 安装来源

- ArchLinuxCN - 稳定版
- 手动编译

### 已安装的插件、版本及安装来源
qv2ray-plugin-command 2.0.0-2
qv2ray-plugin-ssr-dev-git 20200924.r91.d551a40-1

以上来自 ArchLinuxCN

## 附加信息

~~这个问题主要责任不仅在于 plasma、Qv2ray、鸭鸭、我懒得 `yay -S`，关键在于 plasma、Qv2ray、鸭鸭、我懒得 `yay -S`~~ 其实我也不知道为什么就这么巧发现这个 bug 了（逃 ~~发这个 issue 总共 kp 三次~~

*请注意打码隐私相关信息。*

**Comment by unknowndev233** [comment]
正在尝试 dev 版本是否仍旧存在问题

**Comment by unknowndev233** [comment]
> 正在尝试 dev 版本是否仍旧存在问题

Qv2ray 2.7.0-alpha2 on Arch Linux x86_64 没有复现这个问题

**Comment by U-v-U** [comment]
New versions are not affected by this problem since an upstream bug preventing this:
https://github.com/itay-grudev/SingleApplication/commit/a121f61ca1e7703f90d78c606bdc40de9ad344cf

**Comment by Eternallove123** [comment]
功能请求：Qv2ray的后置代理设置，v2ray通过其他代理链接！！！

**Comment by unknowndev233** [comment]
> New versions are not affected by this problem since an upstream bug is preventing two instances from communicating.
> [itay-grudev/SingleApplication@a121f61](https://github.com/itay-grudev/SingleApplication/commit/a121f61ca1e7703f90d78c606bdc40de9ad344cf)

这是上游错误啊

**Comment by DuckSoft** [comment]
dev 已修。
