### ISSUE TITLE
StringFromFile memory leaks

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#314]
```cpp
Indirect leak of 232 byte(s) in 1 object(s) allocated from:
    #0 0x7f442cb648f8 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x7f442b4be334 in QFile::QFile(QString const&) (/usr/lib/libQt5Core.so.5+0x1d1334)
    #2 0x55e256b40377 in Qv2ray::core::connection::ConnectionIO::GetRegularConnections(QStringList) ../Qv2ray/src/core/connection/ConnectionIO.cpp:25
    #3 0x55e256bc8992 in MainWindow::OnConfigListChanged(bool) ../Qv2ray/src/ui/w_MainWindow.cpp:354
    #4 0x55e256bc5b37 in MainWindow::MainWindow(QWidget*) ../Qv2ray/src/ui/w_MainWindow.cpp:221
    #5 0x55e256c1d2cd in main ../Qv2ray/src/main.cpp:448
    #6 0x7f442ad41152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```

Tracing to pos 2:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/core/connection/ConnectionIO.cpp#L25

Tracing to `_ReadConnection`:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/core/connection/ConnectionIO.cpp#L8-L18

The problematic line:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/core/connection/ConnectionIO.cpp#L10

Here, `QFile` created with `new` but is not destructed properly.

---
Inspecting `StringFromFile` in `QvHelpers.cpp`:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/common/QvHelpers.cpp#L21-L28

Here `QFile` object reference is passed, and, `QFile->close()` is called.
However, this method will not destruct the QFile object. Memory leak persists.

**Comment by DuckSoft** [comment]
fixed.
