### ISSUE TITLE
QTranslator memory leak

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#315]
```cpp
Indirect leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7f442cb648f8 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x7f442b5cd104 in QTranslator::QTranslator(QObject*) (/usr/lib/libQt5Core.so.5+0x2e0104)
    #2 0x55e256c1bdd2 in main ../Qv2ray/src/main.cpp:283
    #3 0x7f442ad41152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```

Pos 1:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/main.cpp#L283

In `QvHelpers.cpp`:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/common/QvHelpers.cpp#L163-L168

Causing a typical memory leak.

**Comment by DuckSoft** [comment]
Fixed in 531915d2c74e93d804c5d5de9ee8f2f366bcc200.
@Qv2ray-dev please review.
