### ISSUE TITLE
QHttpServer memory leak

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#316]
```cpp
Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f442cb648f8 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x7f442b5c6a12 in QObject::QObject(QObject*) (/usr/lib/libQt5Core.so.5+0x2d9a12)
    #2 0x55e256b0a1dc in Qv2ray::components::pac::PACServer::PACServer() ../Qv2ray/src/components/pac/QvPACHandler.cpp:12
    #3 0x55e256bc3df1 in MainWindow::MainWindow(QWidget*) ../Qv2ray/src/ui/w_MainWindow.cpp:128
    #4 0x55e256c1d2cd in main ../Qv2ray/src/main.cpp:448
    #5 0x7f442ad41152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```

Pos 2:
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/components/pac/QvPACHandler.cpp#L12

Here `new QHttpServer()` is invocated, but never destructed, causing a leak.

**Comment by DuckSoft** [comment]
Fixed.
