### ISSUE TITLE
PACServer memory leak

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/Qv2ray#317]
```cpp
Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f442cb648f8 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x7f442b5c6a12 in QObject::QObject(QObject*) (/usr/lib/libQt5Core.so.5+0x2d9a12)
    #2 0x55e256b0a1dc in Qv2ray::components::pac::PACServer::PACServer() ../Qv2ray/src/components/pac/QvPACHandler.cpp:12
    #3 0x55e256bc3df1 in MainWindow::MainWindow(QWidget*) ../Qv2ray/src/ui/w_MainWindow.cpp:128
    #4 0x55e256c1d2cd in main ../Qv2ray/src/main.cpp:448
    #5 0x7f442ad41152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```

https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/ui/w_MainWindow.cpp#L128

---
also:
```cpp
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f442cb648f8 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x55e256b0ba6d in QMetaObject::Connection QObject::connect<void (QHttpServer::*)(QHttpRequest*, QHttpResponse*), void (Qv2ray::components::pac::PACServer::*)(QHttpRequest*, QHttpResponse*)>(QtPrivate::FunctionPointer<void (QHttpServer::*)(QHttpRequest*, QHttpResponse*)>::Object const*, void (QHttpServer::*)(QHttpRequest*, QHttpResponse*), QtPrivate::FunctionPointer<void (Qv2ray::components::pac::PACServer::*)(QHttpRequest*, QHttpResponse*)>::Object const*, void (Qv2ray::components::pac::PACServer::*)(QHttpRequest*, QHttpResponse*), Qt::ConnectionType) /usr/include/qt/QtCore/qobject.h:266
    #2 0x55e256b0a22f in Qv2ray::components::pac::PACServer::PACServer() ../Qv2ray/src/components/pac/QvPACHandler.cpp:13
    #3 0x55e256bc3df1 in MainWindow::MainWindow(QWidget*) ../Qv2ray/src/ui/w_MainWindow.cpp:128
    #4 0x55e256c1d2cd in main ../Qv2ray/src/main.cpp:448
    #5 0x7f442ad41152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```
https://github.com/Qv2ray/Qv2ray/blob/38d94d73d2c3a54ec28bc9881ec072441b4eeb87/src/components/pac/QvPACHandler.cpp#L13

**Comment by DuckSoft** [comment]
Fixed.
